appender.console.type = Console
appender.console.name = console

appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %p [%C, line: %L] %m%n

rootLogger.level = debug
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = console
