# --- General ---
pdfapilot.path=/opt/pdfapilot/pdfaPilot

# --- Flags Analyzer---
pdfapilot.quickpdfinfo=true

# --- Flags Creator---
pdfapilot.quick=true
pdfapilot.noprogress=true
pdfapilot.substitute=true
pdfapilot.onlypdfa=true
pdfapilot.fontfolder=/opt/pdfapilot/fontfolder

# Default PDF/A level (used if no value is provided)
pdfapilot.level=2b