# --- General ---
pdfapilot.path=/opt/pdfapilot/pdfaPilot
# time in minutes
pdfapilot.fileDeleteTime=120

# --- Flags Version ---
pdfapilot.version.version=--version

# --- Flags Analyzer---
pdfapilot.analyzer.quickpdfinfo=true

# --- Flags Creator---
pdfapilot.creator.quick=true
pdfapilot.creator.noprogress=true
pdfapilot.creator.substitute=true
pdfapilot.creator.onlypdfa=true
pdfapilot.creator.overwrite=false
pdfapilot.creator.fontfolder=/opt/pdfapilot/fontfolder
pdfapilot.creator.language=de

#--- Flags and Options Report
# report is generated only if pdfapilot.quick is false
pdfapilot.report=false
pdfapilot.report.type=JSON
pdfapilot.report.generate=ALWAYS
pdfapilot.report.path=/var/cache/tomcat/temp/report

# Default PDF/A level (used if no value is provided)
pdfapilot.level=2b
