# --- General ---
pdfapilot.path=/opt/pdfapilot/pdfaPilot

# --- Flags Analyzer---
pdfapilot.quickpdfinfo=true

# --- Flags Creator---
pdfapilot.quick=false
pdfapilot.noprogress=true
pdfapilot.substitute=true
pdfapilot.onlypdfa=true
pdfapilot.overwrite=false
pdfapilot.fontfolder=/opt/pdfapilot/fontfolder

#--- Flags and Options Report
# report is generated only if pdfapilot.quick is false
pdfapilot.report=true
pdfapilot.report.type=JSON
pdfapilot.report.generate=ALWAYS
pdfapilot.report.path=/var/cache/tomcat/temp/report

# Default PDF/A level (used if no value is provided)
pdfapilot.level=2b
